---
title: 'Homework 3: dplyr and ggplot continued'
author: "Penny Kahn"
date: "9/26/2019"
output: 
  html_document:
    keep_md: TRUE
    theme: yeti
---

Pick three of the six tasks below, and produce:

* a tibble, using dplyr as your data manipulation tool;
* an accompanying plot of data from the tibble, using ggplot2 as your visualization tool; and
* some dialogue about what your tables/figures show (doesn’t have to be much).

Or, make up your own task(s)! If you want to do something comparable but different, i.e. swap one quantitative variable for another, be my guest! If you are feeling inspired and curious, then we’re doing this right. Go for it. Just write down the task that you are now doing. Between the dplyr coverage in class and the list below, I think you get the idea.

Relax about the following things:

* Your figure does not have to depict every single number from the data aggregation result. Use your judgement. It just needs to complement the table, add context, and allow for some sanity checking both ways.
* Tidying/reshaping is NOT your assignment. Many of your tables will be awkwardly shaped in the report. That’s OK.
* Table beauty is not a big deal. Simply printing to “screen” is fine.

Tip: Treat this assignment as a “cheat sheet” for future-you! Don’t assume that you’ll remember the lessons you learned while writing this assignment. Write things down:

* Add notes on difficulties/oddities you encountered. For example, which figures are easy/hard to make, which data formats make better inputs for plotting functions vs. for human-friendly tables.
* Provide attribution whenever you take code or an idea from somewhere else, whether a blog post, a colleague, a vignette, etc. Putting those pointers in your “cheat sheet” will be useful for future-you – and it’s just good practice to indicate where you got things from.

### _Task Option 1_
Report the absolute and/or relative abundance of countries with low life expectancy over time by continent: Compute some measure of worldwide life expectancy – you decide – a mean or median or some other quantile or perhaps your current age. Then determine how many countries on each continent have a life expectancy less than this benchmark, for each year.

### _Task Option 2_
Get the maximum and minimum of GDP per capita for all continents.

### _Task Option 3_
Look at the spread of GDP per capita within the continents.

### _Task Option 4_
Compute a trimmed mean of life expectancy for different years. Or a weighted mean, weighting by population. Just try something other than the plain vanilla mean.

### _Task Option 5_
How is life expectancy changing over time on different continents?

### _Task Option 6_
Find countries with interesting stories. Open-ended and, therefore, hard. Promising but unsuccessful attempts are encouraged. This will generate interesting questions to follow up on in class.

## Optional Exercise (2%)
Get table and figure side-by-side. This gist might get you started.